# Central protocol and GitHub release limits
CHUNK_SIZE_MIB = 1900
CHUNK_SIZE_BYTES = CHUNK_SIZE_MIB * 1024 * 1024
MAX_RELEASE_ASSETS = 1000
RESERVED_RELEASE_ASSETS = 1
MAX_DATA_ASSETS = MAX_RELEASE_ASSETS - RESERVED_RELEASE_ASSETS
MAX_RELEASE_DATA_BYTES = CHUNK_SIZE_BYTES * MAX_DATA_ASSETS
MANIFEST_NAME = "manifest.json"
CATALOG_NAME = "catalog.json"
GITHUB_API = "https://api.github.com"
GITHUB_UPLOADS = "https://uploads.github.com"
GITHUB_API_VERSION = "2026-03-10"
SUPPORTED_CHANNELS = ("stable", "beta", "dev", "nightly", "archive")
